# Generated by Django 5.2.5 on 2026-09-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessprofile',
            name='payment_terms',
            field=models.TextField(blank=True, default='Payment is due within 30 days. Please use the invoice number as your payment reference.'),
        ),
    ]
