# Generated by Django 5.2.5 on 2026-09-09 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_alter_businessprofile_payment_terms'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('content', models.BinaryField()),
            ],
        ),
    ]
